var id = "1215";
export default [{
  id: ++id,
  img: require('@/views/follow/assets/1.png'),
  name: "朋友圈",
  url: "/follow"
}, {
  id: ++id,
  img: require('@/views/follow/assets/2.jpg'),
  name: "读书",
  url: "/follow",
  count: 35
}, {
  id: ++id,
  img: require('@/views/follow/assets/3.jpg'),
  name: "手绘",
  url: "/follow",
  count: 1
}, {
  id: ++id,
  img: require('@/views/follow/assets/4.jpg'),
  name: "@IT·互联网",
  url: "/follow",
  count: 7
}, {
  id: ++id,
  img: require('@/views/follow/assets/5.jpg'),
  name: "阿特otter",
  url: "/follow",
  count: 3
}, {
  id: ++id,
  img: require('@/views/follow/assets/6.jpg'),
  name: "一只支",
  url: "/follow",
  count: 2
}, {
  id: ++id,
  img: require('@/views/follow/assets/7.jpg'),
  name: "王小麦",
  url: "/follow",
  count: 5
}]
